#!/bin/sh

source `dirname $0`/includes.sh

ISSUES=
REMOTE=origin

while getopts "ir:" opt ; do
    case "$opt" in
        i) ISSUES="issues" ;;
        r) REMOTE=$OPTARG ;;
        *) echo "Unrecognized option: $opt" ; exit 1 ;;
    esac
done

BRANCH=`git rev-parse --abbrev-ref HEAD`

URL=`git remote -v | grep $REMOTE | head -1 | awk '{ print $2 }' | cut -f 2- -d '@' | sed -e 's/:/\//g' | sed -e 's/\.git//'`


if [ "$BRANCH" != "master" -a "main" ] ; then
    URL="https://$URL/tree/$BRANCH"
else
    URL="https://$URL/$ISSUES"
fi

echo Opening $URL
open $URL