#!/bin/bash

source `dirname $0`/includes.sh

DELETE="-d"
REMOTE=false

while getopts ':fr' OPTION; do
    case "$OPTION" in
        f) DELETE="-D" ;;
        r) REMOTE=true ;;
    esac
done

shift "$(($OPTIND -1))"

BRANCH=$1

git branch $DELETE $BRANCH

if [ $REMOTE == "true" ] ; then
	git push --delete origin $BRANCH
fi
