#!/bin/bash

source `dirname $0`/includes.sh

REMOTE=false

while getopts ':r' OPTION; do
    case "$OPTION" in
        r) REMOTE=true ;;
    esac
done

shift "$(($OPTIND -1))"

BRANCH=$1

git branch -d $BRANCH

if [ $REMOTE == "true" ] ; then
	git push -d origin $BRANCH
fi
