#!/bin/bash

set -euo pipefail

# Only output color if the command isn't being piped.
if [ -t 1 ]; then
  COLOR="always"
else
  COLOR="auto"
fi

REMOTE=origin
BRANCH=master
LOCAL=false
EMAIL=`git config user.email`
AUTHOR="--author=\"$EMAIL\""

if [ `git branch | grep " main$" | wc -l` != 0 ] ; then
    BRANCH=main
fi

function usage() {
    exit -1
}

while getopts "ab:r:l" OPTION; do
    case $OPTION in
        b) BRANCH=$OPTARG ;;
        r) REMOTE=$OPTARG ;;
        l) LOCAL=true ;;
        a) AUTHOR="" ;;
        *) usage ;;
    esac
done
shift $((OPTIND -1))


if [ "$LOCAL" == "true" ] ; then
    TARGET=$BRANCH
else
    TARGET="$REMOTE/$BRANCH"
fi

echo "Showing log of local workspace compared to $TARGET"
CMD="git log --color="$COLOR" --oneline $TARGET...HEAD $AUTHOR"

eval $CMD
