#!/bin/bash

source `dirname $0`/includes.sh

REMOTE=true
REMOTE_NAME=origin

while getopts 'r:l' OPTION; do
    case "$OPTION" in
        l) REMOTE=false ;;
        r) REMOTE_NAME=$OPTARG ;;
    esac
done

shift "$(($OPTIND -1))"

BRANCH=$1

git checkout -b $BRANCH

if [ $REMOTE == "true" ] ; then
    git push -u $REMOTE_NAME $BRANCH
fi

