#!/bin/bash

REMOTE=false

while getopts ':r' OPTION; do
    case "$OPTION" in
        r) REMOTE=true ;;
    esac
done

shift "$(($OPTIND -1))"

BRANCH=$1

git checkout -b $BRANCH

if [ $REMOTE == "true" ] ; then
    git push -u origin $1
fi

