#!/usr/bin/env bash

set -euo pipefail

MERGE=false
REBASE=true
UPSTREAM=upstream
MASTER=master

if git branch | grep -c " main$" &> /dev/null  ; then
    MASTER=main
fi

while getopts "b:u:rm" OPTION; do
    case $OPTION in
        b) MASTER=$OPTARG ;;
        u) UPSTREAM=$OPTARG ;;
        r) REBASE=true ;
           MERGE=false ;;
        m) MERGE=true ;
           REBASE=false ;;
        *) usage ;;
    esac
done
shift $((OPTIND -1))

CUR=$( git branch --show-current )

git fetch --all -p && \
    git checkout "$MASTER" && \
    git rebase "$UPSTREAM/$MASTER" && \
    git push && \
    git checkout "$CUR"

if [ "$MERGE" == "true" ] ; then
    git merge "$MASTER"
fi

if [ "$REBASE" == "true" ] ; then
    git rebase "$MASTER"
fi
