#!/bin/bash

MERGE=false
UPSTREAM=upstream
BRANCH=master

while getopts "b:mu:" OPTION; do
    case $OPTION in
        b) BRANCH=$OPTARG ;;
        m) MERGE=true ;;
        u) UPSTREAM=$OPTARG ;;
        *) usage ;;
    esac
done
shift $((OPTIND -1))

CUR=`git branch --show-current`


git fetch $UPSTREAM && \
    git checkout master && \
    git merge $UPSTREAM/$BRANCH &&
    git checkout $CUR

if [ "$MERGE" == "true" ] ; then
    git merge master
fi


