#!/bin/bash

CONFIRM=no

while getopts "y" opt ; do
    case $opt in
        y) CONFIRM="yes" ;;
    esac
done

git fetch --all &>/dev/null
git fetch --prune &>/dev/null

#git branch -vv | grep 'gone]' | awk '{print $1}' | xargs git branch -D
COUNT=`git branch -vv | grep "gone]" | wc -l`

if [ "$COUNT" == "0" ] ; then
    echo No orphaned branches found.
    exit 0
fi

BRANCHES=`git branch -vv | grep "gone]" | awk '{print $1}'`

if [ "$BRANCHES" != "" ] ; then
    if [ "$CONFIRM" == "no" ] ; then
        echo "The following branches will be deleted:"
        echo $BRANCHES
        #sed -e 's/  */ /g'
        read -p "Press enter to continue, or CTRL-C to cancel."
    fi

    #git branch --merged | egrep -v "(^\*|master|dev) #  | xargs git branch -d
    git branch -vv | grep "gone\]" | awk '{ print $1 }' | xargs git branch -D
else
    echo "No orphaned branches"
fi
