#!/bin/bash

MERGE=false
REBASE=true
UPSTREAM=upstream
BRANCH=master

if [ `git branch | grep " main$" | wc -l` != 0 ] ; then
    BRANCH=main
fi

while getopts "b:u:rm" OPTION; do
    case $OPTION in
        b) BRANCH=$OPTARG ;;
        u) UPSTREAM=$OPTARG ;;
        r) REBASE=true ; MERGE=false ;;
        m) MERGE=true ; REBASE=false ;;
        *) usage ;;
    esac
done
shift $((OPTIND -1))

CUR=`git branch --show-current`

git fetch --all -p && \
    git checkout $BRANCH && \
    git rebase $UPSTREAM/$BRANCH &&
    git checkout $CUR

if [ "$MERGE" == "true" ] ; then
    git merge $BRANCH
fi

if [ "$REBASE" == "true" ] ; then
    git rebase $BRANCH
fi
