#!/bin/bash
#su $USERNAME -l -c "google-drive-ocamlfuse -label $1 $*"

MOUNT=/home/jdlee/GoogleDrive

if [ "$1" == "-f" ] ; then
    sudo umount -fl $MOUNT
    killall -9 google-drive-ocamlfuse 2>/dev/null
fi

mount | grep $MOUNT >/dev/null || { /usr/bin/google-drive-ocamlfuse $MOUNT ; ll $MOUNT ; } #&>/dev/null &
exit 0
