#!/bin/bash

source `dirname $0`/includes.sh

if [ "$@" == "" ] ; then
    echo "A command line must be provided"
    exit -1
fi

COUNT=1

foo() {
    echo Ran for $COUNT attempts
}

register_exit foo

echo -n -e "\033]0;First iteration\007"
while eval "$@"; do 
    COUNT=$(( COUNT+1 ))  ;
    echo -n -e "\033]0;$COUNT successful iteration(s)\007"
    pause
done

echo "Run failed after $COUNT attempts"
