#!/bin/bash

source `dirname $0`/includes.sh

if [ "$1" == "" ] ; then
    echo "A command line must be provided"
    exit -1
fi

COUNT=1

foo() {
    echo Ran for $COUNT attempts
}

register_exit foo

while eval "$@"; do 
    COUNT=$(( COUNT+1 ))  ;
    echo $COUNT
    pause
done

echo "Run failed after $COUNT attempts"
